version: '3.8'

services:
  mysql:
    build: ./Microservices/Databases/Mysql  
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306" 
    volumes:
      - ./Microservices/Databases/Mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
