# Dockerfile for PostgreSQL

FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminpassword
ENV POSTGRES_DB=flightdb

# Expose port 5432 for PostgreSQL
EXPOSE 5432

# Default command to run PostgreSQL
CMD ["postgres"]
