# Dockerfile for MySQL
FROM mysql:8

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=mysqldb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=1234

# Expose port 3306 for MySQL
EXPOSE 3306

# Default command to run MySQL
CMD ["mysqld"]
