version: '3'

services:
  create-service:
    build: ./create-service
    ports:
      - "5001:5001"  # Expondrá el puerto 5000 dentro del contenedor al puerto 5001 de la EC2
    environment:
      - DB_HOST=3.236.166.199  # Aquí va la IP pública de la otra EC2 que tendrá la base de datos
      - DB_USER=user
      - DB_PASSWORD=12345
      - DB_NAME=mysqldb