services:
  create-service:
    build: .
    ports:
      - "5001:5001"  
    environment:
      - DB_HOST=mysql  
      - DB_USER=user
      - DB_PASSWORD=12345
      - DB_NAME=mysqldb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge